### ISSUE TITLE
Pictures?

### ISSUE THREAD

**Issue by federic0** [mike-linus/IOT#1]
Hi Mike, very interesting work. You seem to refer to some picture with the soldering locations but I can't find any pictures... Where can I see them?

Cheers

**Comment by mike-linus** [comment]
Hi

Sorry for the late response. I was looking for an easy way to add pics but instead just added a blog entry at http://mattala.com.au/mike/2016/08/14/airduino-network-enabling-the-daikin-vrv-with-the-brc1d61-or-similar-thermostats/.

Hope it helps.

Cheers
Mike

**Comment by federic0** [comment]
Thanks a lot Mike, I’ll give it a try and let you know!

Cheers 

Federico
